---
name: Publish the component to ESP Component Registry

on:
  release:
    types:
      - published
jobs:
  publish-esp-component-registry:
    uses: esp-idf-lib/shared_workflows/.github/workflows/publish-esp-component-registry.yml@main
    secrets:
      api_token: ${{ secrets.ESP_TOKEN }}
    with:
      components: |
        template-component:.
